version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=car_app_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - system_network

  rabbitmq:
    # image: rabbitmq:3.9-management
    build:
      context: ./config/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - system_network
    # volumes:
    #   - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    #   - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
      # - ./config/rabbitmq/init.sh:/init.sh
      # - ./config/rabbitmq/wait-for-it.sh:/wait-for-it.sh
    # command: >
    #   bash -c "rabbitmq-server start & ./wait-for-it.sh localhost:5672 -- /init.sh"

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      # - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - MONGODB_URL=mongodb://root:password@mongodb:27017/car_app_db?authSource=admin
      - API_BHUT_URL=${API_BHUT_URL}
      - API_BHUT_USERNAME=${API_BHUT_USERNAME}
      - API_BHUT_PASSWORD=${API_BHUT_PASSWORD}
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - system_network
    volumes:
      - ./api:/usr/src/app  # Mapeia o diretório ./app do host para /usr/src/app no container
      - /usr/src/app/node_modules
      - /usr/src/app/dist
  consumer:
    build: ./consumer
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      # - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - MONGODB_URL=mongodb://root:password@mongodb:27017/car_app_db?authSource=admin
    depends_on:
      - rabbitmq
      - mongodb
      - api
    networks:
      - system_network
    volumes:
      - ./consumer:/usr/src/app  # Mapeia o diretório ./app do host para /usr/src/app no container
      - /usr/src/app/node_modules
      - /usr/src/app/dist
      
volumes:
  mongodb_data:

networks:
  system_network:
    driver: bridge